import type { Metadata } from "next";

import "./globals.css";

import Layouts from "@/common/components/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-body m-0 p-0 pt-14 bg-body font-app text-body leading-normal overflow-y-scroll scroll-smooth text-rendering-optimize">
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
